__title__ = 'clicktypes'
__description__ = 'Additional parameter types for the "click" module that I find useful.'
__url__ = 'https://github.com/python-modules/clicktypes'
__version__ = '0.0.1'
__author__ = 'gbe0'
__author_email__ = 'python@gbe0.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2021 gbe0'